"""知识学习报告生成器 (Knowledge Learning Report Generator)。

:class:`KnowledgeReportGenerator` 把 :class:`KnowledgeGraph` (可选叠加
pipeline 处理报告) 转换为一份自包含的「航天知识学习报告」HTML,
辅助论文写作: 核心概念分析、知识空白识别、文献引用、公式速查、推导链路、
以及内嵌的交互式知识云图。

报告结构 (7 节)
---------------
1. 标题: 航天知识学习报告
2. 知识概览: 各类型节点数 + 知识图谱可视化
3. 概念网络分析: 核心概念 Top 10 / 聚类 / 知识空白
4. 文献学习记录 (若提供 pipeline_report): 已读文献 / 关键发现 / 研究趋势
5. 论文写作辅助: 引用列表 / 概念定义表 / 公式速查表 / 推导链路图
6. 知识云图嵌入 (iframe srcdoc, 自包含)
7. 下一步学习建议

风格: 深色专业航天工程报告, 内联 CSS, 与 report.py 一致 (紫色品牌色为主)。
"""

from __future__ import annotations

import base64
import datetime
import html
import os
from collections import defaultdict, deque
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

__all__ = ["KnowledgeReportGenerator"]

# 节点类型中文名与颜色 (与 knowledge_cloud 保持一致)
_TYPE_INFO = {
    "concept": {"name": "概念", "color": "#4B3FE3"},
    "formula": {"name": "公式", "color": "#22A5F7"},
    "tool": {"name": "工具", "color": "#27D2BF"},
    "mission": {"name": "任务", "color": "#F87454"},
    "paper": {"name": "文献", "color": "#1DC981"},
}

# 关系中文名
_REL_NAMES = {
    "depends_on": "依赖",
    "used_by": "被使用",
    "alternative_to": "替代",
    "constraint_of": "约束",
}


class KnowledgeReportGenerator:
    """生成「航天知识学习报告」HTML, 辅助论文写作。"""

    DEFAULT_OUTPUT = "/workspace/reports/knowledge_learning_report.html"

    def __init__(self) -> None:
        # 延迟导入, 避免 rag <-> reporting 循环依赖
        self._cloud_gen = None

    @property
    def cloud_generator(self):
        """延迟获取 KnowledgeCloudGenerator 实例。"""
        if self._cloud_gen is None:
            from ..rag.knowledge_cloud import KnowledgeCloudGenerator
            self._cloud_gen = KnowledgeCloudGenerator()
        return self._cloud_gen

    # ==================================================================
    # 主入口
    # ==================================================================
    def generate(
        self,
        knowledge_graph: Any,
        pipeline_report: Optional[Union[dict, Any]] = None,
        output_path: str = DEFAULT_OUTPUT,
        embed_cloud: bool = True,
        cloud_output_path: Optional[str] = None,
    ) -> str:
        """生成知识学习报告 HTML, 返回文件绝对路径。

        参数
        -----
        knowledge_graph   : :class:`KnowledgeGraph`
        pipeline_report   : 文献处理报告 (可选), 可为 dict 或含 .result 的对象,
                            需含 papers / key_findings / trends 等字段
        output_path       : 报告 HTML 输出路径
        embed_cloud       : 是否内嵌知识云图 (iframe srcdoc, 自包含)
        cloud_output_path : 同时把云图存为独立文件的路径 (可选)
        """
        kg = knowledge_graph
        pr = self._normalize_pipeline_report(pipeline_report)

        # --- 生成知识云图 HTML (用于内嵌) ---
        cloud_html = ""
        cloud_iframe = ""
        if embed_cloud:
            # 始终通过 _build_html 获取 HTML 字符串 (generate 返回的是路径)
            cloud_html = self.cloud_generator._build_html(
                self.cloud_generator.export_graph_data(kg),
                "航天知识云图", snapshots=None,
            )
            # 若指定独立文件路径, 额外保存一份
            if cloud_output_path:
                os.makedirs(os.path.dirname(os.path.abspath(cloud_output_path)),
                            exist_ok=True)
                with open(cloud_output_path, "w", encoding="utf-8") as f:
                    f.write(cloud_html)
            # 用 iframe srcdoc 内嵌 (自包含, 允许加载 D3 CDN)
            cloud_iframe = self._build_cloud_iframe(cloud_html)
        elif cloud_output_path:
            self.cloud_generator.generate(kg, output_path=cloud_output_path)

        # --- 组装报告 ---
        parts: List[str] = []
        parts.append('<!DOCTYPE html><html lang="zh-CN"><head>')
        parts.append('<meta charset="UTF-8">')
        parts.append('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
        parts.append(f"<title>航天知识学习报告</title>")
        parts.append(f"<style>{_REPORT_CSS}</style>")
        parts.append("</head><body><div class='container'>")

        parts.append(self._section_title(kg))
        parts.append(self._section_overview(kg))
        parts.append(self._section_concept_analysis(kg))
        if pr:
            parts.append(self._section_literature(kg, pr))
        parts.append(self._section_writing_aid(kg, pr))
        if cloud_iframe:
            parts.append(self._section_cloud(cloud_iframe))
        parts.append(self._section_next_steps(kg))

        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        parts.append(
            f"<footer>Generated by aerospace_agent.reporting.KnowledgeReportGenerator "
            f"&middot; {now} &middot; Self-contained HTML</footer>")
        parts.append("</div></body></html>")

        html_content = "\n".join(parts)
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        return os.path.abspath(output_path)

    # ==================================================================
    # 知识空白识别
    # ==================================================================
    def identify_knowledge_gaps(self, knowledge_graph: Any) -> List[str]:
        """识别知识空白, 返回描述字符串列表。

        识别规则:
        1. 度数为 0 的孤立节点 (完全无连接)
        2. concept 类型节点未连接到任何 paper 类型节点 (缺少文献支撑)
        3. concept 节点度数 = 1 (仅单一依赖, 知识链薄弱)
        """
        kg = knowledge_graph
        gaps: List[str] = []

        # 度数统计
        degree_map = self._degree_map(kg)

        # 规则 1: 孤立节点
        for nid, deg in degree_map.items():
            if deg == 0:
                n = kg.nodes[nid]
                type_name = _TYPE_INFO.get(n["type"], {}).get("name", n["type"])
                gaps.append(
                    f"孤立节点 [{type_name}] \"{nid}\": "
                    f"度数=0, 完全无连接。建议补充关联关系或移除。"
                )

        # 找到所有 paper 节点
        paper_ids = {nid for nid, n in kg.nodes.items() if n["type"] == "paper"}

        # 规则 2: concept 未连接到 paper (若有 paper 节点)
        if paper_ids:
            for nid, n in kg.nodes.items():
                if n["type"] != "concept":
                    continue
                # 检查是否通过任意路径连接到 paper 节点 (1-2 跳)
                reachable_papers = self._reachable_types(kg, nid, "paper", max_depth=2)
                if not reachable_papers:
                    gaps.append(
                        f"概念 \"{nid}\" 缺少文献支撑: "
                        f"在 2 跳内未连接到任何 paper 节点。"
                        f"建议补充相关文献并建立 used_by 关系。"
                    )

        # 规则 3: 度数=1 的 concept (知识链薄弱)
        for nid, deg in degree_map.items():
            if deg == 1 and kg.nodes[nid]["type"] == "concept":
                gaps.append(
                    f"概念 \"{nid}\" 知识链薄弱: 度数=1, "
                    f"仅单一关联。建议补充依赖/约束关系以丰富推导链。"
                )

        if not gaps:
            gaps.append("未发现明显知识空白, 知识图谱结构较为完整。")

        return gaps

    # ==================================================================
    # BibTeX 引用列表生成
    # ==================================================================
    def generate_citation_list(self, papers: Sequence[dict]) -> str:
        """从文献列表生成 BibTeX 格式引用字符串。

        每篇文献 dict 支持字段: title, authors/author, year, journal/venue,
        doi, url, type (默认 article)。
        """
        if not papers:
            return "% (无文献数据)"

        entries: List[str] = []
        for i, p in enumerate(papers):
            if not isinstance(p, dict):
                continue
            key = self._bibtex_key(p, i)
            etype = p.get("type", p.get("entry_type", "article"))
            lines = [f"@{etype}{{{key},"]

            title = p.get("title", "Untitled")
            lines.append(f"  title     = {{{title}}},")

            authors = p.get("authors") or p.get("author") or "Unknown"
            lines.append(f"  author    = {{{authors}}},")

            year = p.get("year", "")
            if year:
                lines.append(f"  year      = {{{year}}},")

            journal = p.get("journal") or p.get("venue") or p.get("publisher", "")
            if journal:
                lines.append(f"  journal   = {{{journal}}},")

            vol = p.get("volume", "")
            if vol:
                lines.append(f"  volume    = {{{vol}}},")

            pages = p.get("pages", "")
            if pages:
                lines.append(f"  pages     = {{{pages}}},")

            doi = p.get("doi", "")
            if doi:
                lines.append(f"  doi       = {{{doi}}},")

            url = p.get("url", "")
            if url:
                lines.append(f"  url       = {{{url}}},")

            # 去掉末尾逗号
            lines[-1] = lines[-1].rstrip(",")
            lines.append("}")
            entries.append("\n".join(lines))

        return "\n\n".join(entries)

    # ==================================================================
    # 内部: 图分析辅助
    # ==================================================================
    def _degree_map(self, kg: Any) -> Dict[str, int]:
        """计算每个节点的度数 (入度+出度)。"""
        deg: Dict[str, int] = defaultdict(int)
        for nid in kg.nodes:
            deg[nid] = 0
        for src, rels in kg.adj.items():
            for rel, lst in rels.items():
                for dst, w in lst:
                    deg[src] += 1
                    deg[dst] += 1
        return dict(deg)

    def _all_neighbors(self, kg: Any, nid: str) -> set:
        """获取节点的所有邻居 (无向, 合并入边与出边)。"""
        nbrs: set = set()
        for dst, rel, w in kg.neighbors(nid):
            nbrs.add(dst)
        # 入边 (radj[nid][relation] = [(src, weight)])
        for rel, lst in kg.radj.get(nid, {}).items():
            for src, w in lst:
                nbrs.add(src)
        return nbrs

    def _connected_components(self, kg: Any) -> List[List[str]]:
        """计算连通分量 (无向), 返回节点 id 列表的列表, 按大小降序。"""
        visited: set = set()
        components: List[List[str]] = []
        for start in kg.nodes:
            if start in visited:
                continue
            comp: List[str] = []
            q: deque = deque([start])
            visited.add(start)
            while q:
                cur = q.popleft()
                comp.append(cur)
                for nbr in self._all_neighbors(kg, cur):
                    if nbr not in visited:
                        visited.add(nbr)
                        q.append(nbr)
            components.append(comp)
        components.sort(key=len, reverse=True)
        return components

    def _core_concepts(self, kg: Any, top_n: int = 10) -> List[Tuple[str, int, str]]:
        """返回度数最高的 Top N 概念 [(id, degree, content)]。"""
        deg = self._degree_map(kg)
        concepts = [(nid, deg.get(nid, 0), kg.nodes[nid]["content"])
                    for nid, n in kg.nodes.items() if n["type"] == "concept"]
        concepts.sort(key=lambda x: x[1], reverse=True)
        return concepts[:top_n]

    def _reachable_types(
        self, kg: Any, start: str, target_type: str, max_depth: int = 2
    ) -> List[str]:
        """BFS 找到 start 在 max_depth 跳内可达的 target_type 节点 id 列表。"""
        if start not in kg.nodes:
            return []
        visited: set = {start}
        q: deque = deque([(start, 0)])
        found: List[str] = []
        while q:
            cur, d = q.popleft()
            if d >= max_depth:
                continue
            for nbr in self._all_neighbors(kg, cur):
                if nbr in visited:
                    continue
                visited.add(nbr)
                if nbr in kg.nodes and kg.nodes[nbr]["type"] == target_type:
                    found.append(nbr)
                q.append((nbr, d + 1))
        return found

    # ==================================================================
    # 内部: pipeline_report 规范化
    # ==================================================================
    def _normalize_pipeline_report(self, pr: Any) -> Optional[dict]:
        """把各种形式的 pipeline_report 统一为 dict。"""
        if pr is None:
            return None
        if hasattr(pr, "result"):
            pr = pr.result
        if isinstance(pr, dict):
            return pr
        if isinstance(pr, list):
            return {"papers": pr}
        return None

    # ==================================================================
    # 内部: BibTeX key 生成
    # ==================================================================
    @staticmethod
    def _bibtex_key(paper: dict, idx: int) -> str:
        """生成 BibTeX citation key: firstauthor + year + titleword。"""
        authors = paper.get("authors") or paper.get("author") or ""
        first_author = ""
        if authors:
            # 取第一个作者姓氏 (and / , 分隔)
            first = str(authors).split(" and ")[0].split(",")[0].split()[0]
            first_author = "".join(ch for ch in first if ch.isalpha())
        year = paper.get("year", "")
        title = paper.get("title", "")
        title_word = ""
        if title:
            for w in str(title).split():
                w = w.strip(".,;:!?\"'")
                if w and len(w) > 2 and w.lower() not in (
                    "the", "a", "an", "of", "for", "and", "in", "on", "to"):
                    title_word = "".join(ch for ch in w if ch.isalpha())
                    break
        parts = [p for p in (first_author.lower(), str(year), title_word.lower()) if p]
        return "_".join(parts) if parts else f"ref{idx + 1}"

    # ==================================================================
    # 内部: 知识云图 iframe
    # ==================================================================
    @staticmethod
    def _build_cloud_iframe(cloud_html: str) -> str:
        """把云图 HTML 包装为 iframe (srcdoc, 自包含)。"""
        # 转义 srcdoc 属性值中的引号与 &
        escaped = html.escape(cloud_html, quote=True)
        return (
            '<iframe class="cloud-iframe" srcdoc="' + escaped + '" '
            'style="width:100%;height:600px;border:1px solid #30363d;'
            'border-radius:10px;background:#0d1117;" '
            'loading="lazy" sandbox="allow-scripts allow-same-origin"></iframe>'
        )

    # ==================================================================
    # HTML 工具
    # ==================================================================
    @staticmethod
    def _table(
        data: Sequence[Sequence[Any]], headers: Sequence[str],
        num_cols: Optional[set] = None,
    ) -> str:
        num_cols = num_cols or set()
        th = "".join(
            f'<th class="{"num" if i in num_cols else ""}">'
            f'{html.escape(str(h))}</th>'
            for i, h in enumerate(headers))
        rows = []
        for row in data:
            cells = "".join(
                f'<td class="{"num" if i in num_cols else ""}">'
                f'{c if isinstance(c, str) and c.startswith("<") else html.escape(str(c))}</td>'
                for i, c in enumerate(row))
            rows.append(f"<tr>{cells}</tr>")
        return f"<table><thead><tr>{th}</tr></thead><tbody>{''.join(rows)}</tbody></table>"

    # ==================================================================
    # 各章节
    # ==================================================================
    def _section_title(self, kg: Any) -> str:
        now = datetime.datetime.now().strftime("%Y-%m-%d")
        return f"""
<header class="title-page">
  <h1>航天知识学习报告</h1>
  <div class="subtitle">Aerospace Knowledge Learning Report</div>
  <div class="meta">
    <div><div class="label">报告日期</div><div class="value">{now}</div></div>
    <div><div class="label">知识节点</div><div class="value">{kg.num_nodes}</div></div>
    <div><div class="label">知识边</div><div class="value">{kg.num_edges}</div></div>
    <div><div class="label">连通分量</div>
         <div class="value">{len(self._connected_components(kg))}</div></div>
  </div>
</header>"""

    def _section_overview(self, kg: Any) -> str:
        type_counts: Dict[str, int] = defaultdict(int)
        for n in kg.nodes.values():
            type_counts[n["type"]] += 1

        kpi_cards = []
        for t, info in _TYPE_INFO.items():
            cnt = type_counts.get(t, 0)
            kpi_cards.append(
                f'<div class="kpi-card" style="border-top:3px solid {info["color"]}">'
                f'<div class="kpi-value" style="color:{info["color"]}">{cnt}</div>'
                f'<div class="kpi-label">{info["name"]} ({t})</div></div>'
            )

        return f"""
<section>
  <h2>1. 知识概览</h2>
  <p>本报告基于航天知识图谱, 统计各类型知识节点数量, 分析概念网络结构,
  识别知识空白, 并为论文写作提供引用与公式速查辅助。</p>
  <div class="kpi-grid">{''.join(kpi_cards)}</div>
  <h3>知识构成</h3>
  {self._table(
    [[_TYPE_INFO[t]["name"], t, type_counts.get(t, 0),
      f'{type_counts.get(t,0)/max(kg.num_nodes,1)*100:.1f}%']
     for t in _TYPE_INFO],
    ["中文名", "类型", "数量", "占比"], num_cols={2, 3})}
</section>"""

    def _section_concept_analysis(self, kg: Any) -> str:
        # 核心概念 Top 10
        core = self._core_concepts(kg, 10)
        core_rows = []
        for i, (nid, deg, content) in enumerate(core, 1):
            core_rows.append([i, nid, deg, content[:60] + ("..." if len(content) > 60 else "")])
        core_table = self._table(core_rows, ["排名", "概念 ID", "度数", "内容摘要"],
                                 num_cols={0, 2}) if core_rows else "<p>(无概念节点)</p>"

        # 聚类分析
        components = self._connected_components(kg)
        cluster_rows = []
        for i, comp in enumerate(components[:10], 1):  # 显示前 10 个聚类
            types_in = set(kg.nodes[nid]["type"] for nid in comp if nid in kg.nodes)
            type_str = ", ".join(sorted(types_in))
            members = ", ".join(comp[:8]) + ("..." if len(comp) > 8 else "")
            cluster_rows.append([i, len(comp), type_str, members])
        cluster_table = self._table(
            cluster_rows, ["聚类", "节点数", "包含类型", "成员 (前8)"],
            num_cols={0, 1}) if cluster_rows else "<p>(无聚类)</p>"

        # 知识空白
        gaps = self.identify_knowledge_gaps(kg)
        gaps_html = "".join(f'<li>{html.escape(g)}</li>' for g in gaps)

        return f"""
<section>
  <h2>2. 概念网络分析</h2>
  <h3>2.1 核心概念 (度数 Top 10)</h3>
  <p>度数越高表示该概念在知识网络中越处于核心枢纽位置。</p>
  {core_table}
  <h3>2.2 概念聚类分析 (连通分量)</h3>
  <p>共 {len(components)} 个连通分量。最大聚类含 {len(components[0]) if components else 0} 个节点。</p>
  {cluster_table}
  <h3>2.3 知识空白识别</h3>
  <ul class="gap-list">{gaps_html}</ul>
</section>"""

    def _section_literature(self, kg: Any, pr: dict) -> str:
        papers = pr.get("papers") or pr.get("read_papers") or pr.get("literature") or []
        findings = pr.get("key_findings") or pr.get("findings") or []
        trends = pr.get("trends") or pr.get("research_trends") or {}

        # 文献列表
        if papers:
            paper_rows = []
            for p in papers:
                if not isinstance(p, dict):
                    continue
                title = p.get("title", "N/A")
                authors = p.get("authors") or p.get("author", "N/A")
                year = p.get("year", "N/A")
                rel = p.get("relevance") or p.get("relevance_score") or p.get("score", "—")
                summary = p.get("summary") or p.get("abstract", "")
                summary = (summary[:80] + "...") if len(summary) > 80 else summary
                paper_rows.append([title, authors, year, rel, summary])
            paper_table = self._table(
                paper_rows,
                ["标题", "作者", "年份", "相关性", "摘要"],
                num_cols={2, 3})
        else:
            paper_table = "<p>(无文献记录)</p>"

        # 关键发现
        findings_html = ""
        if findings:
            findings_html = "<h3>3.2 关键发现汇总</h3><ul class='finding-list'>"
            for f in findings:
                findings_html += f"<li>{html.escape(str(f))}</li>"
            findings_html += "</ul>"

        # 研究趋势 (按年份统计)
        trends_html = ""
        if papers:
            year_counts: Dict[str, int] = defaultdict(int)
            for p in papers:
                if isinstance(p, dict) and p.get("year"):
                    year_counts[str(p["year"])] += 1
            if year_counts:
                sorted_years = sorted(year_counts.items())
                trend_rows = [[y, c, "█" * c] for y, c in sorted_years]
                trends_html = (
                    "<h3>3.3 研究趋势分析 (按发表年份)</h3>"
                    + self._table(trend_rows, ["年份", "文献数", "分布"], num_cols={1}))
            elif trends:
                trends_html = f"<h3>3.3 研究趋势</h3><pre class='trend-pre'>{html.escape(str(trends))}</pre>"

        return f"""
<section>
  <h2>3. 文献学习记录</h2>
  <p>共记录 {len(papers)} 篇文献。</p>
  <h3>3.1 已读文献列表</h3>
  {paper_table}
  {findings_html}
  {trends_html}
</section>"""

    def _section_writing_aid(self, kg: Any, pr: Optional[dict]) -> str:
        # 推荐引用 (从 paper 节点或 pipeline_report)
        papers = []
        if pr:
            papers = pr.get("papers") or pr.get("read_papers") or pr.get("literature") or []
        # 也从图谱 paper 节点提取
        for nid, n in kg.nodes.items():
            if n["type"] == "paper":
                papers.append({
                    "title": n["content"],
                    "authors": n.get("metadata", {}).get("authors", ""),
                    "year": n.get("metadata", {}).get("year", ""),
                    "journal": n.get("metadata", {}).get("journal", ""),
                    "doi": n.get("metadata", {}).get("doi", ""),
                })

        bibtex = self.generate_citation_list(papers) if papers else "% (暂无文献数据)"
        citation_html = (
            f'<h3>4.1 推荐引用文献 (BibTeX)</h3>'
            f'<pre class="bibtex-block">{html.escape(bibtex)}</pre>'
        )

        # 概念定义表
        concept_nodes = [(nid, n["content"]) for nid, n in kg.nodes.items()
                         if n["type"] == "concept"]
        concept_rows = [[i + 1, nid, content] for i, (nid, content) in
                        enumerate(sorted(concept_nodes))]
        concept_table = self._table(
            concept_rows, ["#", "概念 ID", "定义/内容"], num_cols={0}) \
            if concept_rows else "<p>(无概念节点)</p>"

        # 公式速查表
        formula_nodes = [(nid, n["content"]) for nid, n in kg.nodes.items()
                         if n["type"] == "formula"]
        formula_rows = [[i + 1, nid, content] for i, (nid, content) in
                        enumerate(sorted(formula_nodes))]
        formula_table = self._table(
            formula_rows, ["#", "公式 ID", "公式说明"], num_cols={0}) \
            if formula_nodes else "<p>(无公式节点)</p>"

        # 推导链路图 (重要概念间的 find_path)
        derivation_html = self._derivation_paths(kg)

        return f"""
<section>
  <h2>4. 论文写作辅助</h2>
  {citation_html}
  <h3>4.2 概念定义表</h3>
  <p>所有 concept 类型节点的定义, 可直接用于论文术语表。</p>
  {concept_table}
  <h3>4.3 公式速查表</h3>
  <p>所有 formula 类型节点, 可用于论文公式索引。</p>
  {formula_table}
  <h3>4.4 推导链路图</h3>
  <p>核心概念间的最短推导路径 (find_path), 揭示知识推导结构。</p>
  {derivation_html}
</section>"""

    def _derivation_paths(self, kg: Any) -> str:
        """生成核心概念间的推导链路。"""
        core = self._core_concepts(kg, 5)
        if len(core) < 2:
            return "<p>(核心概念不足, 无法生成推导链路)</p>"

        # 从度数最高的概念出发, 找到其他核心概念的最短路径
        hub = core[0][0]
        paths_html = []
        for nid, deg, _ in core[1:]:
            path = kg.find_path(hub, nid)
            if path and len(path) > 1:
                # 构建可读链路
                chain = " → ".join(path)
                # 标注每段关系
                annotated = []
                for i in range(len(path) - 1):
                    annotated.append(path[i])
                    # 找关系
                    rel_label = "?"
                    for dst, rel, w in kg.neighbors(path[i]):
                        if dst == path[i + 1]:
                            rel_label = _REL_NAMES.get(rel, rel)
                            break
                    annotated.append(f' <span class="path-rel">[{rel_label}]</span> → ')
                annotated.append(path[-1])
                paths_html.append(
                    f'<div class="path-chain">{"".join(annotated)}</div>')
            elif path:
                paths_html.append(f'<div class="path-chain">{path[0]} (自身)</div>')

        if not paths_html:
            return "<p>(核心概念间无可达路径)</p>"

        return f'<div class="path-list">{"".join(paths_html)}</div>'

    def _section_cloud(self, cloud_iframe: str) -> str:
        return f"""
<section>
  <h2>5. 知识云图</h2>
  <p>下方为交互式力导向知识云图 (内嵌自包含 HTML, 需联网加载 D3.js CDN)。
  支持拖拽、缩放、搜索、类型筛选、点击查看详情、双击折叠邻居。</p>
  {cloud_iframe}
  <p class="caption">提示: 若云图未显示, 可能是浏览器阻止了 iframe 内脚本,
  可单独打开 knowledge_cloud.html 查看。</p>
</section>"""

    def _section_next_steps(self, kg: Any) -> str:
        gaps = self.identify_knowledge_gaps(kg)
        components = self._connected_components(kg)

        suggestions: List[str] = []

        # 基于知识空白
        isolated = [g for g in gaps if "孤立节点" in g]
        if isolated:
            suggestions.append("处理孤立节点: 补充关联关系或移除冗余节点, 提升图谱连通性。")

        no_paper = [g for g in gaps if "缺少文献支撑" in g]
        if no_paper:
            suggestions.append(
                f"补充文献支撑: 发现 {len(no_paper)} 个概念缺少 paper 节点连接, "
                "建议检索相关文献并建立 used_by 关系。"
            )

        weak = [g for g in gaps if "知识链薄弱" in g]
        if weak:
            suggestions.append(
                f"强化知识链: 发现 {len(weak)} 个概念度数仅 1, "
                "建议补充 depends_on / constraint_of 关系以丰富推导。"
            )

        # 基于聚类
        if len(components) > 1:
            suggestions.append(
                f"整合知识孤岛: 图谱含 {len(components)} 个连通分量, "
                "建议在分量间建立桥接关系, 形成统一知识网络。"
            )

        # 基于类型覆盖
        type_counts: Dict[str, int] = defaultdict(int)
        for n in kg.nodes.values():
            type_counts[n["type"]] += 1
        if type_counts.get("paper", 0) == 0:
            suggestions.append(
                "补充文献节点: 图谱中尚无 paper 类型节点, "
                "建议将已读文献加入图谱并关联相关概念。"
            )
        if type_counts.get("formula", 0) < 3:
            suggestions.append(
                "丰富公式库: 公式节点较少, 建议补充关键推导公式 (如 Tsiolkovsky 方程、"
                "Lambert 解等)。"
            )

        if not suggestions:
            suggestions.append("知识图谱结构较为完整, 建议持续更新文献并深化概念间关系。")

        sugg_html = "".join(f"<li>{html.escape(s)}</li>" for s in suggestions)
        return f"""
<section>
  <h2>6. 下一步学习建议</h2>
  <p>基于知识空白识别与网络结构分析, 提出以下学习与完善建议:</p>
  <ol class="suggestion-list">{sugg_html}</ol>
</section>"""


# ---------------------------------------------------------------------------
# 内联 CSS (深色专业航天风格, 与 report.py 一致)
# ---------------------------------------------------------------------------
_REPORT_CSS = """
* { box-sizing: border-box; }
body {
  margin: 0; padding: 0;
  background: #0d1117; color: #e6edf3;
  font-family: -apple-system, "Segoe UI", "Noto Sans", "Noto Sans CJK SC",
               "WenQuanYi Micro Hei", Roboto, Helvetica, Arial, sans-serif;
  font-size: 15px; line-height: 1.7;
}
.container { max-width: 1100px; margin: 0 auto; padding: 24px; }
header.title-page {
  text-align: center; padding: 50px 24px 36px;
  background: linear-gradient(135deg, #161b22 0%, #0d1117 100%);
  border-bottom: 3px solid #4B3FE3;
  border-radius: 12px 12px 0 0;
}
header.title-page h1 {
  font-size: 2.2em; margin: 0 0 10px; color: #a5b4fc; letter-spacing: 1px;
}
header.title-page .subtitle { color: #8b949e; font-size: 1.05em; }
header.title-page .meta {
  margin-top: 22px; display: flex; justify-content: center; gap: 28px;
  flex-wrap: wrap; color: #c9d1d9;
}
header.title-page .meta div { text-align: center; }
header.title-page .meta .label { font-size: 0.72em; color: #6e7681;
  text-transform: uppercase; letter-spacing: 1px; }
header.title-page .meta .value { font-size: 1.1em; font-weight: 600; color: #58a6ff; }

section {
  background: #161b22; margin: 20px 0; padding: 26px;
  border-radius: 10px; border: 1px solid #30363d;
}
section h2 {
  color: #a5b4fc; border-bottom: 2px solid #30363d;
  padding-bottom: 10px; margin-top: 0; font-size: 1.45em;
}
section h3 { color: #7ee787; margin-top: 22px; font-size: 1.12em; }
section p { color: #c9d1d9; }

table {
  border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 0.9em;
}
th, td { border: 1px solid #30363d; padding: 8px 11px; text-align: left; }
th { background: #21262d; color: #58a6ff; font-weight: 600; }
tr:nth-child(even) td { background: #0d1117; }
td.num, th.num { text-align: right; font-family: "SFMono-Regular", Consolas, monospace; }

.kpi-grid {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: 14px; margin: 16px 0;
}
.kpi-card {
  background: #0d1117; border: 1px solid #30363d; border-radius: 8px;
  padding: 16px; text-align: center;
}
.kpi-card .kpi-value { font-size: 2em; font-weight: 700; font-family: monospace; }
.kpi-card .kpi-label { font-size: 0.78em; color: #8b949e;
  text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }

.gap-list { list-style: none; padding: 0; }
.gap-list li {
  background: #1a1f2e; border-left: 4px solid #f0883e;
  padding: 10px 14px; margin: 8px 0; border-radius: 4px; color: #d29922;
  font-size: 0.9em;
}
.finding-list li, .suggestion-list li {
  background: #0d1117; border: 1px solid #30363d;
  padding: 10px 14px; margin: 6px 0; border-radius: 6px; color: #c9d1d9;
}
.suggestion-list { counter-reset: sugg; }
.suggestion-list li { border-left: 3px solid #4B3FE3; }

.bibtex-block {
  background: #0d1117; border: 1px solid #30363d; border-radius: 8px;
  padding: 16px; margin: 12px 0; overflow-x: auto;
  font-family: "SFMono-Regular", Consolas, monospace; font-size: 0.85em;
  color: #7ee787; white-space: pre; line-height: 1.5;
}
.trend-pre {
  background: #0d1117; border: 1px solid #30363d; border-radius: 8px;
  padding: 14px; font-family: monospace; font-size: 0.85em; color: #c9d1d9;
  white-space: pre-wrap;
}

.path-list { margin: 12px 0; }
.path-chain {
  background: #0d1117; border: 1px solid #30363d; border-left: 3px solid #4B3FE3;
  border-radius: 6px; padding: 12px 16px; margin: 8px 0;
  font-family: monospace; font-size: 0.88em; color: #c9d1d9;
  line-height: 1.8; word-break: break-all;
}
.path-rel { color: #d2a8ff; font-size: 0.85em; }

.cloud-iframe { display: block; margin: 12px 0; }
.caption { color: #8b949e; font-size: 0.85em; font-style: italic; margin-top: 8px; }

footer {
  text-align: center; color: #6e7681; font-size: 0.85em;
  padding: 24px; border-top: 1px solid #30363d; margin-top: 24px;
}

@media (max-width: 720px) {
  .container { padding: 12px; }
  section { padding: 16px; }
  header.title-page h1 { font-size: 1.6em; }
  header.title-page .meta { gap: 16px; }
}
"""


# ---------------------------------------------------------------------------
# 自测: 用预填充知识图谱生成学习报告
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    from ..rag.knowledge_graph import KnowledgeGraph

    print("=== knowledge_report 自测 ===")
    kg = KnowledgeGraph()
    kg.prepopulate()
    print(f"知识图谱: 节点={kg.num_nodes}, 边={kg.num_edges}")

    gen = KnowledgeReportGenerator()

    # 知识空白识别
    gaps = gen.identify_knowledge_gaps(kg)
    print(f"\n知识空白 ({len(gaps)} 项):")
    for g in gaps[:5]:
        print(f"  - {g}")

    # 核心概念
    core = gen._core_concepts(kg, 5)
    print(f"\n核心概念 Top 5:")
    for nid, deg, _ in core:
        print(f"  - {nid}: 度数={deg}")

    # 连通分量
    comps = gen._connected_components(kg)
    print(f"\n连通分量: {len(comps)} 个, 最大含 {len(comps[0])} 节点")

    # BibTeX (模拟)
    sample_papers = [
        {"title": "Optimal Trajectories for Lunar Transfer",
         "authors": "Bate, R. and Mueller, D.", "year": 2020,
         "journal": "Journal of Spacecraft", "doi": "10.2514/1.XXXX"},
        {"title": "Patched Conic Approximation Revisited",
         "authors": "Vallado, D.", "year": 2019,
         "journal": "Celestial Mechanics"},
    ]
    bibtex = gen.generate_citation_list(sample_papers)
    print(f"\nBibTeX 引用:\n{bibtex}")

    # 生成报告
    out = gen.generate(kg, pipeline_report={"papers": sample_papers,
                                            "key_findings": ["Hohmann 转移为最优能量方案",
                                                             "相位角匹配决定发射窗口"]})
    size_kb = os.path.getsize(out) / 1024
    print(f"\n知识学习报告已生成: {out}")
    print(f"文件大小: {size_kb:.1f} KB")

    print("\nknowledge_report 自测通过.")
